version: '3'
services:
    db:
        image: mysql:5.7
        volumes:
            - ./database/db-init:/docker-entrypoint-initdb.d
        restart: always
        environment:
            - MYSQL_USER=mysql
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=products
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - 32769:3306
    backend:
        build:
            dockerfile: ./Dockerfile
            context: ./backend
        ports:
            - "8081:8081"
    frontend:
        build:
            dockerfile: ./Dockerfile
            context: ./frontend
        ports:
            - "8080:8080"